image: node:24

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

stages:
  - install
  - check
  - build
  - publish

install:
  stage: install
  script:
    - npm ci

check:
  stage: check
  needs:
    - install
  script:
    - npm run check

build:
  stage: build
  needs:
    - install
  script:
    - npm run build:js
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

publish-to-npm:
  stage: publish
  needs:
    - build
    - check
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
    - npm publish --access public
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

publish-to-npm-beta:
  stage: publish
  needs:
    - build
    - check
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
    - npm publish --access public --tag beta
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+$/
