image: node:24

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

stages:
  - install
  - check
  - build
  - publish
  - notify

install:
  stage: install
  script:
    - npm ci

check:
  stage: check
  needs:
    - install
  script:
    - npm run check

build:
  stage: build
  needs:
    - install
  script:
    - npm run build:dist
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

publish-to-npm:
  stage: publish
  needs:
    - build
    - check
  script:
    - echo "registry=https://registry.npmjs.org/" > ./.npmrc
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ./.npmrc
    - npm publish --access public --registry https://registry.npmjs.org/
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

publish-to-npm-beta:
  stage: publish
  needs:
    - build
    - check
  script:
    - echo "registry=https://registry.npmjs.org/" > ./.npmrc
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ./.npmrc
    - npm publish --access public --tag beta --registry https://registry.npmjs.org/
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+$/

notify-slack:
  stage: notify
  needs:
    - job: publish-to-npm
      optional: true
    - job: publish-to-npm-beta
      optional: true
  script:
    - npm run notify
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-beta\.[0-9]+)?$/
