image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - check
  - build
  - publish

check:
  stage: check
  script:
    - npm install
    - npm run check

build:
  stage: build
  script:
    - npm run build
  needs:
    - check

deploy-to-npm:
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
    - npm publish --access public
  needs:
    - build
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches

deploy-to-npm-beta:
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
    - npm publish --access public --tag beta
  needs:
    - build
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+$/
  except:
    - branches
